version: '3.8'

services:
    mongo:
      image: mongo:3.6.19-xenial
      ports:
        - '27018:27018'
      volumes:
        - data:/data/db
    
    backend:
      build: ./backend
      image: omondijeff/yolo/backend
      ports:
        - '3001:3001'
      depends_on:
        - mongo
      environment:
        - PORT=3001
      volumes:
        - ./backend:/server
    client:
      build: ./client
      image: omondijeff/yolo/client
      stdin_open: true
      ports:
        - '3000:3000'
      depends_on: 
        - backend
      volumes:
       - ./client/src:/app/src

volumes:
  data: