apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: omondijeff/yolo/backend
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
          volumeMounts:
            - mountPath: /server
              name: backend-data
      volumes:
        - name: backend-data
          configMap:
            name: backend-config
